#!/usr/bin/env bash
#script that transfers a file from our client to a serve

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
